# Generated by Django 4.0.2 on 2024-07-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('article_text', models.TextField()),
            ],
        ),
    ]
