# Generated by Django 4.0.2 on 2024-06-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('interests', models.TextField()),
                ('partner_preferences', models.TextField()),
                ('event_preferences', models.TextField()),
            ],
        ),
    ]
